#!/usr/bin/env python3
"""Render the 32-pixel Unitree U/lightning design; writes only BMP-backed ICO."""
from pathlib import Path
from PIL import Image

# U silhouette reference: https://www.unitree.com/unitree-favicon.svg
# Pixel adaptation + lightning, 2026-09-19. '#' black, '.' white; no smoothing.
PIXELS = """
................................
................................
................................
................................
................................
.....#########.........########.
.....#########........#########.
.....########.........#########.
.....########.....##..########..
....#########....###..########..
....#########....##..#########..
....########....###..#########..
....########...###...########...
...#########...#####.########...
...#########..###############...
...########.....###.#########...
...########.....##..########....
..#########....###..########....
..#########....##..#########....
..########....##...#########....
..########....#....########.....
.#########.........########.....
.#########........#########.....
.##########......##########.....
.#########################......
.#########################......
..######################........
................................
................................
................................
................................
................................
""".strip().splitlines()
root = Path(__file__).resolve().parents[1]
base = Image.new('RGB', (32, 32), 'white')
assert len(PIXELS) == 32 and all(len(row) == 32 for row in PIXELS)
for y, row in enumerate(PIXELS):
    for x, pixel in enumerate(row):
        if pixel == '#':
            base.putpixel((x,y), (0,0,0))
nearest = getattr(Image, 'Resampling', Image).NEAREST
frames = [base.resize((n,n), nearest) for n in (16,32,48)]
frames[-1].save(root/'assets/quadlink78.ico', format='ICO', sizes=[(16,16),(32,32),(48,48)],
               append_images=frames[:-1], bitmap_format='bmp')
